using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dapper.Scaffold.Domain;

public class GeneratedFile : GeneratedObject
{
    private readonly List<string> _usings = new();
    private GeneratedClass _class = new();

    public string Namespace { get; set; }

    public static string GetAutoGeneratedComment()
    {
        var commentText = new StringBuilder();

        commentText.AppendLine("// <auto-generated>");
        commentText.AppendLine("// This code was generated by a tool.");
        commentText.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        commentText.AppendLine("// </auto-generated>");
        commentText.AppendLine();
        commentText.AppendLine("#nullable enable");
        commentText.AppendLine();

        return commentText.ToString();
    }

    public void AddClass(GeneratedClass generatedClass)
    {
        generatedClass.BaseIndentation = BaseIndentation;
        _class = generatedClass;
    }

    public string RegisterDbType(string dbType)
    {
        switch (dbType.ToLower())
        {
            case "bigint":
            case "timestamp":
                return "long";
            case "binary":
            case "image":
            case "varbinary":
                return "byte[]";
            case "bit":
                return "bool";
            case "char":
            case "nchar":
            case "ntext":
            case "nvarchar":
            case "text":
            case "varchar":
                return "string";
            case "date":
            case "datetime":
            case "datetime2":
            case "smalldatetime":
                AddUsing("System");
                return "DateTime";
            case "datetimeoffset":
                AddUsing("System");
                return "DateTimeOffset";
            case "decimal":
            case "money":
            case "numeric":
            case "smallmoney":
                return "decimal";
            case "float":
                return "double";
            case "int":
                return "int";
            case "real":
                return "float";
            case "smallint":
                return "short";
            case "time":
                AddUsing("System");
                return "TimeSpan";
            case "tinyint":
                return "byte";
            case "uniqueidentifier":
                AddUsing("System");
                return "Guid";
        }

        return $"UNKNOWN_{dbType}";
    }

    public override string ToString()
    {
        _output = new();

        _output.Append(GetAutoGeneratedComment());

        if (_usings.Count > 0)
        {
            foreach (var usingNamespace in _usings)
            {
                AppendLine($"using {usingNamespace};");
            }

            AppendLine(string.Empty);
        }

        AppendLine($"namespace {Namespace};");
        AppendLine();

        _output.Append(_class);

        return _output.ToString();
    }

    public string GetListMethod()
    {
        var methodText = new StringBuilder();

        methodText.AppendLine(
            $"    public static async Task<List<{_class.Name}>> Get{_class.Name}ListAsync(this IDbConnection connection, string? whereClause = null, object? param = null)");

        methodText.AppendLine("    {");
        methodText.AppendLine("        if (whereClause == null)");
        methodText.AppendLine("        {");
        methodText.AppendLine($"            var selectQuery = \"SELECT * FROM [{_class.TableName}]\";");
        methodText.AppendLine($"            var response = (await connection.QueryAsync<{_class.Name}>(selectQuery)).ToList();");
        methodText.AppendLine();
        methodText.AppendLine("            return response;");
        methodText.AppendLine("        }");
        methodText.AppendLine("        else");
        methodText.AppendLine("        {");
        methodText.AppendLine($"            var selectQuery = $\"SELECT * FROM [{_class.TableName}] WHERE {{whereClause}}\";");
        methodText.AppendLine($"            var response = (await connection.QueryAsync<{_class.Name}>(selectQuery, param)).ToList();");
        methodText.AppendLine();
        methodText.AppendLine("            return response;");
        methodText.AppendLine("        }");
        methodText.AppendLine("    }");

        return methodText.ToString();
    }

    public string GetInsertMethod()
    {
        var writeColumns = _class.Properties.Where(p => p.Name != _class.IdentityColumn && !p.Readonly).ToList();
        var readColumns = _class.Properties.Where(p => p.Name == _class.IdentityColumn || p.Readonly).ToList();
        var defaultColumns = writeColumns.Where(x => x.HasDefault).ToList();

        if (!defaultColumns.Any())
        {
            return GetBasicInsertMethod(writeColumns, readColumns);
        }

        return GetAdvancedInsertMethod(writeColumns, readColumns, defaultColumns);
    }

    public string GetGetByIdMethod()
    {
        var identityColumn = _class.Properties.FirstOrDefault(p => p.Name == _class.IdentityColumn);

        if (identityColumn == null)
        {
            return string.Empty;
        }

        var methodText = new StringBuilder();

        methodText.AppendLine($"    public static async Task<{_class.Name}?> Get{_class.Name}ByIdAsync(this IDbConnection connection, {identityColumn.Type} id)");

        methodText.AppendLine("    {");
        methodText.AppendLine($"        var selectQuery = \"SELECT * FROM [{_class.TableName}] WHERE [{identityColumn.Name}] = @id\";");
        methodText.AppendLine($"        var response = await connection.QueryFirstOrDefaultAsync<{_class.Name}>(selectQuery, new {{ id }});");
        methodText.AppendLine();
        methodText.AppendLine("        return response;");
        methodText.AppendLine("    }");

        return methodText.ToString();
    }

    public string GetSaveMethod()
    {
        var identityColumn = _class.Properties.FirstOrDefault(p => p.Name == _class.IdentityColumn);

        if (identityColumn == null)
        {
            return string.Empty;
        }

        var methodText = new StringBuilder();

        methodText.AppendLine($"    public static async Task SaveAsync(this IDbConnection connection, {_class.Name} obj)");
        methodText.AppendLine("    {");
        methodText.AppendLine($"        if (obj.{identityColumn.Name} == default)");
        methodText.AppendLine("        {");
        methodText.AppendLine("            await connection.InsertAsync(obj);");
        methodText.AppendLine("        }");
        methodText.AppendLine("        else");
        methodText.AppendLine("        {");
        methodText.AppendLine("            await connection.UpdateAsync(obj);");
        methodText.AppendLine("        }");
        methodText.AppendLine("    }");

        return methodText.ToString();
    }

    public string GetUpdateMethod()
    {
        var identityColumn = _class.Properties.FirstOrDefault(p => p.Name == _class.IdentityColumn);

        if (identityColumn == null)
        {
            return string.Empty;
        }

        var writeColumns = _class.Properties.Where(p => p.Name != _class.IdentityColumn && !p.Readonly).ToList();
        var methodText = new StringBuilder();

        methodText.AppendLine($"    public static async Task UpdateAsync(this IDbConnection connection, {_class.Name} obj)");
        methodText.AppendLine("    {");

        methodText.AppendLine(
            $"        var updateQuery = \"UPDATE [{_class.TableName}] SET {string.Join(", ", writeColumns.Select(x => $"[{x.Name}] = @{x.Name}"))} WHERE [{identityColumn.Name}] = @{identityColumn.Name}\";");

        methodText.AppendLine("        var rowsAffected = await connection.ExecuteAsync(updateQuery, obj);");
        methodText.AppendLine();
        methodText.AppendLine("        if (rowsAffected == 0)");
        methodText.AppendLine("        {");
        methodText.AppendLine("            await connection.InsertAsync(obj);");
        methodText.AppendLine("        }");
        methodText.AppendLine("    }");

        return methodText.ToString();
    }

    public string GetDeleteMethod()
    {
        var identityColumn = _class.Properties.FirstOrDefault(p => p.Name == _class.IdentityColumn);

        if (identityColumn == null)
        {
            return string.Empty;
        }

        var methodText = new StringBuilder();

        methodText.AppendLine($"    public static async Task DeleteAsync(this IDbConnection connection, {_class.Name} obj)");
        methodText.AppendLine("    {");
        methodText.AppendLine($"        var deleteQuery = \"DELETE FROM [{_class.TableName}] WHERE [{identityColumn.Name}] = @{identityColumn.Name}\";");
        methodText.AppendLine();
        methodText.AppendLine("        await connection.ExecuteAsync(deleteQuery, obj);");
        methodText.AppendLine($"        obj.{identityColumn.Name} = default;");
        methodText.AppendLine("    }");

        return methodText.ToString();
    }

    private string GetAdvancedInsertMethod(List<GeneratedProperty> writeColumns, List<GeneratedProperty> readColumns, List<GeneratedProperty> defaultColumns)
    {
        var nonDefaultColumns = writeColumns.Where(x => !x.HasDefault).ToList();
        var methodText = new StringBuilder();

        methodText.AppendLine($"    public static async Task InsertAsync(this IDbConnection connection, {_class.Name} obj)");
        methodText.AppendLine("    {");
        methodText.AppendLine($"        var insertColumns = new List<string> {{ {string.Join(", ", nonDefaultColumns.Select(x => $"\"{x.Name}\""))} }};");

        if (readColumns.Any())
        {
            methodText.AppendLine($"        var outputColumns = new List<string> {{ {string.Join(", ", readColumns.Select(x => $"\"{x.Name}\""))} }};");
        }
        else
        {
            methodText.AppendLine("        var outputColumns = new List<string>();");
        }

        methodText.AppendLine();

        foreach (var column in defaultColumns)
        {
            methodText.AppendLine($"        if (obj.{column.Name} != default) {{ insertColumns.Add(\"{column.Name}\"); }} else {{ outputColumns.Add(\"{column.Name}\"); }}");
        }

        if (defaultColumns.Any())
        {
            methodText.AppendLine();
        }

        methodText.AppendLine(
            "        var outputString = outputColumns.Any() ? $\"OUTPUT {string.Join(\", \", outputColumns.Select(x => $\"INSERTED.[{x}]\"))} \" : string.Empty;");

        methodText.AppendLine(
            $"        var insertQuery = $\"INSERT INTO [{_class.TableName}] ({{string.Join(\", \", insertColumns.Select(c => $\"[{{c}}]\"))}}) {{outputString}}VALUES ({{string.Join(\", \", insertColumns.Select(c => $\"@{{c}}\"))}});\";");

        methodText.AppendLine($"        var insertedObj = await connection.QueryFirstOrDefaultAsync<{_class.Name}>(insertQuery, obj);");
        methodText.AppendLine();

        foreach (var readColumn in readColumns)
        {
            methodText.AppendLine($"        obj.{readColumn.Name} = insertedObj?.{readColumn.Name} ?? default;");
        }

        foreach (var column in defaultColumns)
        {
            methodText.AppendLine($"        if (obj.{column.Name} == default) {{ obj.{column.Name} = insertedObj?.{column.Name} ?? default; }}");
        }

        methodText.AppendLine("    }");

        return methodText.ToString();
    }

    private string GetBasicInsertMethod(List<GeneratedProperty> writeColumns, List<GeneratedProperty> readColumns)
    {
        var outputString = readColumns.Any() ? $"OUTPUT {string.Join(", ", readColumns.Select(x => $"INSERTED.[{x.Name}]"))} " : string.Empty;
        var methodText = new StringBuilder();

        methodText.AppendLine($"    public static async Task InsertAsync(this IDbConnection connection, {_class.Name} obj)");
        methodText.AppendLine("    {");

        methodText.AppendLine(
            $"        var insertQuery = \"INSERT INTO [{_class.TableName}] ({string.Join(", ", writeColumns.Select(x => $"[{x.Name}]"))}) {outputString}VALUES ({string.Join(", ", writeColumns.Select(x => $"@{x.Name}"))});\";");

        if (readColumns.Any())
        {
            methodText.AppendLine($"        var insertedObj = await connection.QueryFirstOrDefaultAsync<{_class.Name}>(insertQuery, obj);");
            methodText.AppendLine();

            foreach (var readColumn in readColumns)
            {
                methodText.AppendLine($"        obj.{readColumn.Name} = insertedObj?.{readColumn.Name} ?? default;");
            }
        }
        else
        {
            methodText.AppendLine("        await connection.ExecuteAsync(insertQuery, obj);");
        }

        methodText.AppendLine("    }");

        return methodText.ToString();
    }

    private void AddUsing(string usingNamespace)
    {
        if (!_usings.Contains(usingNamespace))
        {
            _usings.Add(usingNamespace);
        }
    }
}
