# Heavyweight build and test
name: Build and Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
  
jobs:
  set-version-number:
    name: Set version number
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.MajorMinorPatch }}
      is-release: ${{ steps.gitversion.outputs.CommitsSinceVersionSource == 0 }}
      #is-release: 'true'
    
    steps:
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.0.0

  build-netcore-tool:
    needs: set-version-number
    name: Build .NET Core (global) tool

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet pack ./Dapper.Scaffold/Dapper.Scaffold.csproj -p:SelfContained=false -p:PackAsTool=true -p:PackageOutputPath=/tmp/dapper-scaffold/nupkg
      env:
        VERSION: ${{ needs.set-version-number.outputs.semVer }}
      
    - name: Upload published tool artifact
      uses: actions/upload-artifact@v4
      if: ${{ needs.set-version-number.outputs.is-release == 'true' }}
      with:
        name: dapper-scaffold-dotnet-tool-${{ needs.set-version-number.outputs.semVer }}
        path: /tmp/dapper-scaffold/nupkg/*   

    - name: Push to Nuget.org
      if: ${{ needs.set-version-number.outputs.is-release == 'true' }}
      run: dotnet nuget push /tmp/dapper-scaffold/nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG_KEY}} --skip-duplicate
  
  build-nuget-package:
    needs: set-version-number
    name: Build Nuget

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Pack Nuget package Dapper.Scaffold
      run: dotnet pack ./Dapper.Scaffold/Dapper.Scaffold.csproj -c Release --include-symbols -o /tmp/dapper-scaffold/nupkg /p:Version=${{ env.VERSION }}
      env:
        VERSION: ${{ needs.set-version-number.outputs.semVer }}

    - name: Push to Nuget.org
      if: ${{ needs.set-version-number.outputs.is-release == 'true' }}
      run: dotnet nuget push /tmp/dapper-scaffold/nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG_KEY}} --skip-duplicate
